### ISSUE TITLE
I'm stuck... any walkthroughs available?

### ISSUE THREAD

**Issue by LotBlind** [mdsteele/azimuth#22]
The hints system has been invaluable so far but I'm in the part where I have all weapons but one (I can see where it is) and all other power-ups but one, in the red part of the map. No idea how to break through the white girders. I'm hoping to get to finish the game before reviewing it for a site I write reviews for.

**Comment by mdsteele** [comment]
Thanks for playing, and hope you're enjoying it!  No one's written a walkthrough that I know of, but I'm always happy to provide help.

If you're referring to these white girders:
<img width="500" alt="Screenshot 2023-05-21 at 10 29 06 PM" src="https://github.com/mdsteele/azimuth/assets/35096/98c80fbb-51c1-472e-93d2-9fb6b2fa1c78">
you will need that last weapon to break through them, which you won't be able to reach until after beating the boss of the red area.

If you send me a screenshot of your minimap so I can see where you've been, I can point you to where you need to go next.

**Comment by LotBlind** [comment]
![image](https://github.com/mdsteele/azimuth/assets/36453326/de61d472-bb6c-45f8-b57e-347fb98e42ad)

I'm very happy I was able to get help here! I tried through Google Groups earlier following some link but I don't think you monitor that one anymore?

Before this I was stuck in the top left-most area where I didn't initially notice you can charge through some walls with the C-Plus Drive. Other than that the hints system has always helped me out... I don't know how much more wandering back and forth there would have been otherwise.

When I've finished the game, I'll review it for Home of the Underdogs. It very obviously belongs there. What percentage of the weapons and upgrades did you take directly from Metroid games and how much is your own invention BTW? I never ended up playing any Metroid titles.

**Comment by mdsteele** [comment]
Thanks.  The yellow arrow on this map shows where you need to go; there's a secret passage near the upper-left corner of that room that will put you a direct path leading to the next boss.

![azimuth-minimap](https://github.com/mdsteele/azimuth/assets/35096/96505530-7b3c-43a3-b7cc-d4e9fb8c1191)

It looks like you've already collected the Milliwave Radar upgrade (which is in the rooms just above there); the intended design was that players would use their brand new Milliwave Radar upon re-entering that larger room, and immediately find the secret passage.  Unfortunately, what I failed to consider when I made the game is that if a player _doesn't_ happen to do that, and then starts wandering the map trying to figure out where to go, there's basically no indication anywhere that that one room is where you need to go back to.  Whoops!  So you aren't the first person to get stuck at this point in the game; sorry about that.

Most of the weapons and upgrades in the game are inspired in one way or another by other games (the Metroid series in particular, but also SketchFighter 4000 Alpha and Gunstar Heroes).  The Tractor Cloak and Orion Booster were both original as far as I can remember right now (I think?), but on the other hand I think those turned out to be pretty weak designs.

**Comment by LotBlind** [comment]
So that was very helpful... I was able to finish the whole game in one sitting from there! The last two boss fights are pretty epic. I especially liked the second-to-last one I think? I think you were getting better as you went along and maybe you made those two last?

Thanks for the other info! This is such a Top Dog for our collection. I'm gonna have enough time to check out what else I might have missed starting from that last save point before the core. Maybe there should be a fast shortcut from that room back to the start of the core area if people like me wanna go back and try and tie up loose ends. It's not entirely obvious perhaps that there won't be any returning to the rest of the map after entering the core after all.

The most scathing criticism I have of this game is actually this: It's way too easy! I died once when experimenting with exploring the lava vents without the heat armor (yeah, that didn't work out!) and like one other time when I was just careless with my shields in some random room somewhere. I never died once to any bosses and I think the core itself was the only one that even got me down to critical health before I got back to a phase of the fight that allowed for farming (after which it wasn't so tense again). Also I wasn't initially even using the beam weapon in the core fight, so I was handicapping myself pretty hard honestly! As a band-aid solution, I would personally make it have two other difficulty settings so that the current one is the easiest, the next one has +50% incoming damage and the last one +100% incoming damage (or maybe even add some to the current base damage first?). That would make the bosses more tense and require more caution and calculation around the rest of the game. Honestly this was a walk in the park. Past that, the next most obvious criticism is the balancing of the bosses, which is always tough to pull off, as it didn't quite feel like they came in order of increasing difficulty here. And maybe some of them are too generous with shield drops even if you pumped up the damage a fair bit?

There was a random typo in the outro text. I think it was in a sentence that contained the word "formidable"?

**Comment by LotBlind** [comment]
I'll put that tip about going for a low % run in my review then. I don't know if I can afford to take the time for a second playthrough myself.

Typo: "the Trichord Alliance is **a still a** formidable enemy" so I was unclear what it was. Grammar mistake.

**Comment by mdsteele** [comment]
> Typo: "the Trichord Alliance is **a still a** formidable enemy" so I was unclear what it was. Grammar mistake.

Haha, whoops.  Thanks for the catch; I'll have to fix that.

**Comment by LotBlind** [comment]
While I remember, the review in question is up now in the last post here: https://homeoftheunderdogs.net/
