### ISSUE TITLE
Musics

### ISSUE THREAD

**Issue by Rayerdyne** [mdsteele/azimuth#9]
Hmm that isn't a real issue, but I don't found any music file under a format I know : only musicXX.txt files in ./data/music, where I read a title, tempo, and raw notes (abcdefg).

Where can I find them ? (I've seen "WAVE file generation" in ./src/muse, so I think I could have find them...)

I actually really enjoyed them (the game, too =), and I wanted to share them to my friend (in accordance with license terms of course).

Another question : the license talks about the program and code, but what about the music ? I actually already covered three of them (attached in pdf), that I didn't published yet (sheet music may don't look very finished, but I mostly didn't want to make mistake with license).
Am I allowed to publish them, for example making records on YouTube or post the sheet music on Musescore ?

I truly congratulate you for this game, that I enjoyed. I know C, I think making a game like that will take me years !

Rayerdyne.

[Azimuth-Barrag.pdf](https://github.com/mdsteele/azimuth/files/3809581/Azimuth-Barrag.pdf)
[Azimuth-Sarvari.pdf](https://github.com/mdsteele/azimuth/files/3809582/Azimuth-Sarvari.pdf)
[Azimuth-Title_screen.pdf](https://github.com/mdsteele/azimuth/files/3809583/Azimuth-Title_screen.pdf)

**Comment by mdsteele** [comment]
> Hmm that isn't a real issue, but I don't found any music file under a format I know : only musicXX.txt files in ./data/music, where I read a title, tempo, and raw notes (abcdefg).
> 
> Where can I find them ? (I've seen "WAVE file generation" in ./src/muse, so I think I could have find them...)

Those are in fact the music files as the game uses them; they're written in a custom format I created for the game.  However, as you've noticed, the `muse` utility includes the ability to convert them to WAV files.  If you're using a *nix shell, you can use it like so:

```shell
# Compile muse:
make out/debug/host/bin/muse
# Generate a 60.0 second WAV file from music01.txt:
./out/debug/host/bin/muse data/music/music01.txt 0 60.0 > music01.wav
```

Let me know if you have any trouble with it.

> I actually really enjoyed them (the game, too =), and I wanted to share them to my friend (in accordance with license terms of course).
> 
> Another question : the license talks about the program and code, but what about the music ? I actually already covered three of them (attached in pdf), that I didn't published yet (sheet music may don't look very finished, but I mostly didn't want to make mistake with license).
> Am I allowed to publish them, for example making records on YouTube or post the sheet music on Musescore ?

Really glad to hear you enjoyed the game!  Yes, I would be delighted if you would use and share the music (and if you do post it anywhere publicly, e.g. Musescore/YouTube, I'd love it if you would email me a link so I can check it out).

The music is already covered under the same license (GPL3+) as the rest of the code, but for the music specifically I'd imagine that something like a Creative Commons license would be much simpler to allow you and others to share it.  So, I will update the README to indicate that the music may be used under a [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

> I truly congratulate you for this game, that I enjoyed. I know C, I think making a game like that will take me years !

As a matter of fact, it took me three and a half years.  (-:  It turned out to be a more ambitious project than I realized at first.

**Comment by Rayerdyne** [comment]
Thank you a lot for this detailed answer !

I'll email you the Musescore link soon (actually I'll look for the titles before).
I plan to make sheet music, but I find that recordings will need a bit more than a piano solo, then I'll look for help :-).

**Comment by mdsteele** [comment]
There's not currently an easy way to get the song's length, sorry.  I only added the WAV feature to help me make the trailer for the game, so I never bothered to make it very user-friendly; I just exported roughly the duration I needed and edited it down from there with another program.

If you do want to try writing your own songs in that format, you can play them with:
```shell
./out/debug/host/bin/muse path/to/your/music.txt
```
But as I'm sure you've noticed, many details of the format (like the instrument settings, drum sounds, and flag jumps) are idiosyncratic and undocumented.  You can look at the code for reading it in [`src/azimuth/util/music.c`](https://github.com/mdsteele/azimuth/blob/master/src/azimuth/util/music.c) if you're feeling brave.  (-:
